server:
  port: 8800
spring:
  application:
    name: eureka-client
eureka:
  instance:
    hostname: eureka.client
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
info:
  application:
    name: ${spring.application.name}