server:
  port: 9000
spring:
  application:
    name: micro-service-user
  cloud:
    bus:
      trace:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: http://10.254.199.52:9091,http://10.254.199.52:9092,http://10.254.199.52:9093
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
eureka:
  instance:
    hostname: micro.service.user
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
info:
  application:
    message: micro-service-user
    name: ${spring.application.name}
    port: ${server.port}