server:
  port: 9100
spring:
  application:
    name: micro-service-user-feign
eureka:
  instance:
    hostname: micro.service.user.feign
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
info:
  application:
    name: ${spring.application.name}
    port: ${server.port}