server:
  # address: 127.0.0.1
  port: 1100
spring:
  application:
    name: zuul
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
    bus:
      trace:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: http://192.168.74.210:9091,http://192.168.74.210:9092,http://192.168.74.210:9093
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul: 
  ignoredServices: '*' # 忽略所有未配置的service
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    micro-service-user: #自定义名称
      path: /micro/user/**
      serviceId: micro-service-user # /user/开头的路径转发至micro-service-user微服务
info:
  application:
    name: ${spring.application.name}
    port: ${server.port}